# Generated by Django 2.2.4 on 2019-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_ctrl', '0002_cronschedule_timelapse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
