# Generated by Django 2.2.4 on 2019-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_ctrl', '0005_remove_generalsettings_send_email_on_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='nb_of_failures_to_reboot_after',
            field=models.IntegerField(default=2, help_text='The system will be rebooted, if the program fails multiple times'),
        ),
    ]
