# Generated by Django 3.2 on 2021-04-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_ctrl', '0007_auto_20191008_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_job_id', models.CharField(max_length=124, null=True)),
                ('name', models.CharField(default='Scheduled Config', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favfield',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='email_subject_prefix',
            field=models.CharField(blank=True, default='[Emils-MacBook-Pro.home]', max_length=64),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historyunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ScheduledConfigField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=124)),
                ('value', models.CharField(max_length=123)),
                ('scheduled_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_ctrl.scheduledconfig')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledconfig',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera_ctrl.cronschedule'),
        ),
    ]
