# Generated by Django 3.2 on 2021-04-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_ctrl', '0008_auto_20210430_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledconfigfield',
            name='scheduled_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='camera_ctrl.scheduledconfig'),
        ),
    ]
