# Generated by Django 3.2 on 2021-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_ctrl', '0009_alter_scheduledconfigfield_scheduled_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledconfigfield',
            name='value',
            field=models.CharField(max_length=124),
        ),
    ]
