# Generated by Django 2.2.4 on 2019-08-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email_on_error', models.BooleanField(default=True)),
                ('send_email_on_timelapse_end', models.BooleanField(default=True)),
                ('log_to_db_timelapse_capture', models.BooleanField(default=False)),
                ('log_to_db_camera_capture', models.BooleanField(default=False)),
                ('autodetect_cameras_on_start', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
