# Generated by Django 2.2.4 on 2019-08-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='send_email_on_timelapse_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='send_email_on_capture_error',
            field=models.BooleanField(default=False),
        ),
    ]
