# Generated by Django 2.2.4 on 2019-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportEmail',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='emails',
            field=models.CharField(blank=True, help_text='Space separated emails', max_length=512),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='log_to_db_camera_capture',
            field=models.BooleanField(default=False, verbose_name='Log camera capture'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='log_to_db_timelapse_capture',
            field=models.BooleanField(default=False, verbose_name='Log timelapse capture'),
        ),
    ]
