# Generated by Django 2.2.4 on 2019-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0002_auto_20190823_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='hard_reset_on_timelapse_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='seconds_to_wait_after_hard_reset',
            field=models.IntegerField(default=2),
        ),
    ]
