# Generated by Django 2.2.4 on 2019-08-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0002_auto_20190820_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='send_email_on_timelapse_end',
        ),
    ]
