# Generated by Django 2.2.4 on 2019-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0004_auto_20190826_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='seconds_to_wait_after_hard_reset',
            field=models.FloatField(default=1.0),
        ),
    ]
