# Generated by Django 2.2.4 on 2019-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0005_auto_20190826_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='send_email_on_sync_error',
            field=models.BooleanField(default=True),
        ),
    ]
