# Generated by Django 2.2.4 on 2019-08-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0006_generalsettings_send_email_on_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='email_subject_prefix',
            field=models.CharField(blank=True, default='macbookprocmm.dyndns.cern.ch', max_length=64),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='log_to_db_camera_capture',
            field=models.BooleanField(default=True, verbose_name='Log camera capture'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='seconds_to_wait_after_hard_reset',
            field=models.FloatField(default=5.0),
        ),
    ]
