# Generated by Django 2.2.4 on 2019-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_settings', '0007_auto_20190830_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='email_subject_prefix',
            field=models.CharField(blank=True, default='unicornslayer', max_length=64),
        ),
    ]
