class ScheduledConfigEvents:
    CONFIG_SET = 'CONFIG_SET'
    CONFIG_MISSING = 'CONFIG_MISSING'
    CONFIG_GET_ERROR = 'CONFIG_GET_ERROR'
    CONFIG_SET_ERROR = 'CONFIG_SET_ERROR'
    CONFIG_FAILED_TO_CHANGE_ERROR = 'CONFIG_FAILED_TO_CHANGE_ERROR'
