# Generated by Django 2.2.3 on 2019-07-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favfield',
            old_name='name_pattern',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='favfield',
            name='label',
        ),
    ]
