# Generated by Django 2.2.3 on 2019-08-06 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontimelapse',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 7, 9, 24, 14, 463499)),
        ),
        migrations.AlterField(
            model_name='crontimelapse',
            name='name',
            field=models.CharField(default='My timelapse', max_length=64),
        ),
    ]
