# Generated by Django 2.2.3 on 2019-08-06 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_control', '0002_auto_20190806_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontimelapse',
            old_name='filename_pattern',
            new_name='filename_format',
        ),
        migrations.AddField(
            model_name='crontimelapse',
            name='capture_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crontimelapse',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 7, 9, 59, 15, 330758)),
        ),
    ]
