# Generated by Django 2.2.3 on 2019-08-06 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_control', '0005_auto_20190806_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontimelapse',
            old_name='storage_dir',
            new_name='storage_dir_format',
        ),
        migrations.AlterField(
            model_name='crontimelapse',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 7, 13, 23, 31, 938901)),
        ),
    ]
