# Generated by Django 2.2.4 on 2019-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
