# Generated by Django 2.2.4 on 2019-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_logging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyunit',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
