# Generated by Django 2.2.4 on 2019-08-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('year', models.CharField(help_text='4 digit year', max_length=128)),
                ('month', models.CharField(help_text='1-12', max_length=128)),
                ('day', models.CharField(help_text='1-31', max_length=256)),
                ('week', models.CharField(help_text='1-53', max_length=256)),
                ('day_of_week', models.CharField(help_text='0-6 or mon, tue, wed, thu, fri, sat, sun', max_length=256)),
                ('hour', models.CharField(help_text='0-23', max_length=128)),
                ('minute', models.CharField(help_text='0-59', max_length=128)),
                ('second', models.CharField(help_text='0-59', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Timelapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_job_id', models.CharField(max_length=124, null=True)),
                ('name', models.CharField(default='Timelapse', max_length=64)),
                ('storage_dir_format', models.CharField(default='./Timelapses/{timelapse_name}_{timelapse_id}', max_length=256)),
                ('filename_format', models.CharField(default='capture_{camera_id}_{capture_index}', max_length=256)),
                ('capture_index', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.CronSchedule')),
            ],
        ),
    ]
