# Generated by Django 2.2.3 on 2019-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('storage_dir_format', models.CharField(max_length=256)),
                ('filename_format', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('year', models.CharField(max_length=128)),
                ('month', models.CharField(max_length=128)),
                ('day', models.CharField(max_length=256)),
                ('week', models.CharField(max_length=256)),
                ('day_of_week', models.CharField(max_length=256)),
                ('hour', models.CharField(max_length=128)),
                ('minute', models.CharField(max_length=128)),
                ('second', models.CharField(max_length=128)),
            ],
        ),
    ]
