# Generated by Django 2.2.3 on 2019-08-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronschedule',
            name='filename_format',
        ),
        migrations.RemoveField(
            model_name='cronschedule',
            name='storage_dir_format',
        ),
        migrations.CreateModel(
            name='Timelapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('storage_dir_format', models.CharField(max_length=256)),
                ('filename_format', models.CharField(max_length=256)),
                ('capture_index', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.CronSchedule')),
            ],
        ),
    ]
