# Generated by Django 2.2.3 on 2019-08-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20190815_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelapse',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='capture_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='filename_format',
            field=models.CharField(default='capture_{camera_id}_{capture_index}', max_length=256),
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='name',
            field=models.CharField(default='Timelapse', max_length=64),
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='storage_dir_format',
            field=models.CharField(default='./Timelapses/{timelapse_name}_{timelapse_id}', max_length=256),
        ),
    ]
