# Generated by Django 2.2.3 on 2019-08-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler', '0002_auto_20180412_0758'),
        ('scheduling', '0003_auto_20190815_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelapse',
            name='schedule_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.DjangoJob'),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='day',
            field=models.CharField(help_text='1-31', max_length=256),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='day_of_week',
            field=models.CharField(help_text='0-6 or mon, tue, wed, thu, fri, sat, sun', max_length=256),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='hour',
            field=models.CharField(help_text='0-23', max_length=128),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='minute',
            field=models.CharField(help_text='0-59', max_length=128),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='month',
            field=models.CharField(help_text='1-12', max_length=128),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='second',
            field=models.CharField(help_text='0-59', max_length=128),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='week',
            field=models.CharField(help_text='1-53', max_length=256),
        ),
        migrations.AlterField(
            model_name='cronschedule',
            name='year',
            field=models.CharField(help_text='4 digit year', max_length=128),
        ),
    ]
