# Generated by Django 2.2.3 on 2019-08-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20190815_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelapse',
            name='schedule_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_apscheduler.DjangoJob'),
        ),
    ]
