# Generated by Django 2.2.3 on 2019-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20190815_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelapse',
            name='schedule_job',
        ),
        migrations.AddField(
            model_name='timelapse',
            name='schedule_job_id',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
