# Generated by Django 2.2.3 on 2019-08-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20190815_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelapse',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.CronSchedule'),
        ),
    ]
